# Generated by Django 6.0.2 on 2026-03-03 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainerRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('nationality', models.CharField(max_length=100)),
                ('country', models.CharField(choices=[('oman', 'عُمان'), ('saudi', 'السعودية'), ('uae', 'الإمارات'), ('kuwait', 'الكويت'), ('qatar', 'قطر'), ('bahrain', 'البحرين'), ('other', 'أخرى')], max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=255)),
                ('document', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Trainer Registration',
                'verbose_name_plural': 'Trainer Registrations',
                'ordering': ['-created_at'],
            },
        ),
    ]
